### ISSUE TITLE
Pull changelog files into release posts

### ISSUE THREAD

**Issue by jewel-andraia** [Reddit-Enhancement-Suite/Reddit-Enhancement-Suite.github.io#18]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/3284

**Comment by jewel-andraia** [comment]
When a new release is created on honestbleeps/RES, copy the new changelog file into https://github.com/Reddit-Enhancement-Suite/Reddit-Enhancement-Suite.github.io/tree/master/_posts

**Comment by benmcgarry** [comment]
Changelogs now automated to website. Should resolve this.
