### ISSUE TITLE
Should known issues posts be included on the releases page?

### ISSUE THREAD

**Issue by Ajedi32** [Reddit-Enhancement-Suite/Reddit-Enhancement-Suite.github.io#25]
I thought this was a bit strange, the known issues posts seem to be included on the releases page. Is that intended?

![screenshot-redditenhancementsuite com 2016-09-02 09-49-26](https://cloud.githubusercontent.com/assets/1876931/18207858/8d970f8a-70f2-11e6-85e3-884fffe5b105.png)

**Comment by jewel-andraia** [comment]
Yes, I deliberately included known issues inline on release page for discoverability.
