### ISSUE TITLE
GitHub isn't a browser

### ISSUE THREAD

**Issue by Ajedi32** [Reddit-Enhancement-Suite/Reddit-Enhancement-Suite.github.io#26]
The current placement of the GitHub icon on the homepage is a bit confusing. :wink: 

![screenshot-redditenhancementsuite com 2016-09-02 09-50-17](https://cloud.githubusercontent.com/assets/1876931/18207927/e6e5d10c-70f2-11e6-9f50-f710c6b7d21b.png)

We have Chrome, Edge, Firefox, Opera, Safari, and... GitHub?

**Comment by jewel-andraia** [comment]
Sure ain't -- but it gets people to GitHub. Mild inconsistency, but I consider it okay as an umbrella of "places you can get RES packages" kind of idea.
