### ISSUE TITLE
What posts are intended to be collapsed on the releases page?

### ISSUE THREAD

**Issue by Ajedi32** [Reddit-Enhancement-Suite/Reddit-Enhancement-Suite.github.io#27]
On `/releases`, it seems that some of the posts are collapsed. Looking at the CSS, it seems that only the most recent post and all pre-release posts are expanded by default:

https://github.com/Reddit-Enhancement-Suite/Reddit-Enhancement-Suite.github.io/blob/c5b6f3e4f266e75d9faa5ef3401058778cbf0ade/releases.html#L51-L52

Is that intended? Seems a bit inconsistent to me.

Also, is there a way for the user to expand collapsed posts? If not, why are we even putting the content for those posts on the page at all?

**Comment by jewel-andraia** [comment]
I intended to show pre-releases after the most recent release, and the most recent release. In theory  the other blocks will be toggleable open, but I need to fix it.
