### ISSUE TITLE
/update-safari.plist pointing to latest version

### ISSUE THREAD

**Issue by jewel-andraia** [Reddit-Enhancement-Suite/Reddit-Enhancement-Suite.github.io#38]
https://gist.github.com/honestbleeps/9631f7ae74d16e0a4140b5e386a3cb5e

**Comment by erikdesjardins** [comment]
Automatic updates no longer work now that the cert is expired (right?)

**Comment by erikdesjardins** [comment]
...actually that doesn't matter, cause we already added it. Might as well keep it. https://github.com/Reddit-Enhancement-Suite/Reddit-Enhancement-Suite.github.io/blob/26a6fc4e3c8a1bd35bdcd4dc69c641051f742299/update-safari.plist
